name: 'app_reporting'
version: '0.4.0'
config-version: 2
models:
  app_reporting:
    +materialized: table
    +schema: app_reporting
    intermediate:
      +materialized: view
      +schema: int_app_reporting
require-dbt-version: [">=1.3.0", "<2.0.0"]
