name: 'app_reporting_integration_tests'
version: '0.5.0'
profile: 'integration_tests'
config-version: 2
vars: 
  # apple_store__using_subscriptions: true # uncomment this line when generating docs!
  # google_play__using_subscriptions: true # uncomment this line when regenerating docs!
  # google_play__using_earnings: true # uncomment this line when regenerating docs!
  google_play_schema: app_reporting_integrations_test_8
  apple_store_schema: app_reporting_integrations_test_8

  google_play_source:
    google_play_stats_installs_app_version_identifier: "stats_installs_app_version"
    google_play_stats_crashes_app_version_identifier: "stats_crashes_app_version"
    google_play_stats_ratings_app_version_identifier: "stats_ratings_app_version"
    google_play_stats_installs_device_identifier: "stats_installs_device"
    google_play_stats_ratings_device_identifier: "stats_ratings_device"
    google_play_stats_installs_os_version_identifier: "stats_installs_os_version"
    google_play_stats_ratings_os_version_identifier: "stats_ratings_os_version"
    google_play_stats_crashes_os_version_identifier: "stats_crashes_os_version"
    google_play_stats_installs_country_identifier: "stats_installs_country"
    google_play_stats_ratings_country_identifier: "stats_ratings_country"
    google_play_stats_store_performance_country_identifier: "stats_store_performance_country"
    google_play_stats_store_performance_traffic_source_identifier: "stats_store_performance_traffic_source"
    google_play_stats_installs_overview_identifier: "stats_installs_overview"
    google_play_stats_crashes_overview_identifier: "stats_crashes_overview"
    google_play_stats_ratings_overview_identifier: "stats_ratings_overview"
    google_play_earnings_identifier: "earnings"
    google_play_financial_stats_subscriptions_country_identifier: "financial_stats_subscriptions_country"

  apple_store_source:
    apple_store_app_identifier: "app_store_app"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_event_summary"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_discovery_and_engagement_standard_daily_identifier: "app_store_discovery_and_engagement_daily"
    apple_store_crash_daily_identifier: "app_crash_daily"
    apple_store_download_standard_daily_identifier: "app_store_download_daily"
    apple_store_session_standard_daily_identifier: "app_session_daily"
    apple_store_installation_and_deletion_standard_daily_identifier: "app_store_installation_and_deletion_daily"

    apple_store__subscription_events:
      - 'Renew'
      - 'Cancel'
      - 'Subscribe'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +persist_docs:
    relation: "{{ false if target.type in ('spark','databricks') else true }}"
    columns: "{{ false if target.type in ('spark','databricks') else true }}"
  +schema: "app_reporting_{{ var('directed_schema','dev') }}" ## To be used for validation testing

seeds:
  app_reporting_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
    stats_installs_overview:
      +column_types:
        active_device_installs: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    stats_ratings_app_version:
      +column_types:
        app_version_code: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"