name: 'app_reporting_integration_tests'
version: '0.4.0'
profile: 'integration_tests'
config-version: 2
vars: 
  google_play_schema: app_reporting_integrations_test_5
  apple_store_schema: app_reporting_integrations_test_5
  google_play_source:
    google_play_stats_installs_app_version_identifier: "stats_installs_app_version"
    google_play_stats_crashes_app_version_identifier: "stats_crashes_app_version"
    google_play_stats_ratings_app_version_identifier: "stats_ratings_app_version"
    google_play_stats_installs_device_identifier: "stats_installs_device"
    google_play_stats_ratings_device_identifier: "stats_ratings_device"
    google_play_stats_installs_os_version_identifier: "stats_installs_os_version"
    google_play_stats_ratings_os_version_identifier: "stats_ratings_os_version"
    google_play_stats_crashes_os_version_identifier: "stats_crashes_os_version"
    google_play_stats_installs_country_identifier: "stats_installs_country"
    google_play_stats_ratings_country_identifier: "stats_ratings_country"
    google_play_stats_store_performance_country_identifier: "stats_store_performance_country"
    google_play_stats_store_performance_traffic_source_identifier: "stats_store_performance_traffic_source"
    google_play_stats_installs_overview_identifier: "stats_installs_overview"
    google_play_stats_crashes_overview_identifier: "stats_crashes_overview"
    google_play_stats_ratings_overview_identifier: "stats_ratings_overview"
    google_play_earnings_identifier: "earnings"
    google_play_financial_stats_subscriptions_country_identifier: "financial_stats_subscriptions_country"

  apple_store_source:
    apple_store_app_identifier: "app"
    apple_store_app_store_platform_version_source_type_report_identifier: "app_store_platform_version_source_type"
    apple_store_app_store_source_type_device_report_identifier: "app_store_source_type_device"
    apple_store_app_store_territory_source_type_report_identifier: "app_store_territory_source_type"
    apple_store_crashes_app_version_device_report_identifier: "crashes_app_version"
    apple_store_crashes_platform_version_device_report_identifier: "crashes_platform_version"
    apple_store_downloads_platform_version_source_type_report_identifier: "downloads_platform_version_source_type"
    apple_store_downloads_source_type_device_report_identifier: "downloads_source_type_device"
    apple_store_downloads_territory_source_type_report_identifier: "downloads_territory_source_type"
    apple_store_sales_account_identifier: "sales_account"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_events"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_usage_app_version_source_type_report_identifier: "usage_app_version_source_type"
    apple_store_usage_platform_version_source_type_report_identifier: "usage_platform_version_source_type"
    apple_store_usage_source_type_device_report_identifier: "usage_source_type_device"
    apple_store_usage_territory_source_type_report_identifier: usage_territory_source_type

    apple_store__subscription_events:
      - 'Renew'
      - 'Cancel'
      - 'Subscribe'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +persist_docs:
    relation: "{{ false if target.type in ('spark','databricks') else true }}"
    columns: "{{ false if target.type in ('spark','databricks') else true }}"
  +schema: "app_reporting_{{ var('directed_schema','dev') }}" ## To be used for validation testing

seeds:
  app_reporting_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
    stats_installs_overview:
      +column_types:
        active_device_installs: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    stats_ratings_app_version:
      +column_types:
        app_version_code: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    app_store_platform_version_source_type:
      +column_types:
        date: timestamp
    crashes_platform_version:
      +column_types:
        date: timestamp
    crashes_app_version:
      +column_types:
        date: timestamp
    downloads_platform_version_source_type:
      +column_types:
        date: timestamp
    app_store_territory_source_type:
      +column_types:
        date: timestamp
    downloads_source_type_device: 
      +column_types:
        date: timestamp
    app_store_source_type_device: 
      +column_types:
        date: timestamp
    usage_source_type_device:
      +column_types:
        date: timestamp
    downloads_territory_source_type:
      +column_types:
        date: timestamp
    usage_territory_source_type: 
      +column_types:
        date: timestamp
    usage_platform_version_source_type: 
      +column_types:
        date: timestamp
    usage_app_version_source_type:
      +column_types:
        date: timestamp
